id: I544EBE3B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:51:53+00:00'
last_modified: '2022-06-08T05:40:31.397750+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16947
  title: ཡ་མཚན་ཆེ་བའི་གླིང་གེ་སར་སྒྲུང་པའི་གསང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0DF8:
      image_group_id: I1KG18460
      title: ''
      total_pages: 226
      order: 1
      base_file: 0DF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
